name: CodeSonar Neovim Build and Analyze

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  BIN_DIR: ${{ github.workspace }}/bin
  INSTALL_PREFIX: ${{ github.workspace }}/nvim-install
  CAFILE: ".github/github.cert.pem" 
  TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  API_URL: https://api.github.com
  CSONAR_HUB_URL: "https://partnerdemo.codesonar.com" 
  CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
  CSONAR_HUB_PASSWORD: "${{ secrets.CSONAR_HUB_PASSWORD }}"
  CSONAR_CSHOME: /opt/codesonar
  CS_USER_HOME: /__w/neovim/neovim
  COMMIT_HASH: ${{ github.sha }}
  REPO_URL: "https://github.com/kenazk/neovim"

jobs:
  CodeSonar_Analyze:
    permissions: write-all
    runs-on: codesecure-runner-set
    container:
      image: ghcr.io/codesecure-se/curl-cso-builder:8.1p0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Set parallelism
        run: echo "PARALLEL=`nproc`" >> $GITHUB_ENV

      - name: Checkout Neovim Source
        uses: actions/checkout@v4

      - name: Safe directory
        run: git config --global --add safe.directory `pwd`

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen

      - name: Build Dependencies
        run: make deps

      - name: Configure Build
        run: |
          cmake -S cmake.deps --preset ci
          cmake --build .deps
          cmake --preset ci

      - name: Checkout CodeSonar CI-Script
        uses: actions/checkout@v4
        with:
          repository: CodeSecure-SE/codesonar_ci
          path: cso-scripts

      - name: Build and Analyze with CodeSonar
        run: python3 cso-scripts/build_and_analyze.py codesonar.conf make -j $PARALLEL CMAKE_BUILD_TYPE=RelWithDebInfo && make install

      - name: Upload SARIF to GitHub # Use this if you do not have GitHub Enterprise
        if: ${{ github.event.pull_request }}
        uses: actions/upload-artifact@v4
        with:
          name: SARIF file
          path: warnings.sarif

      - name: Push Summary Report
        if: ${{ github.event.pull_request }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: warnings.md

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: warnings.sarif
          category: "CodeSecure CodeSonar"
